DELETE FROM "Hourly"."BSC6900UMTS@Cell@PS_RAB_Setup" WHERE "Result Time" <now()::date- 15;;
DELETE FROM "Hourly"."BTS3900@Cell@PDCP" WHERE "Result Time" <now()::date- 15;;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Immediate_Assignment" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Assignment" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Cell_Status" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RRC_Connection_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@Site@FlexAbis" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Short_Message" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RRC_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RRC_Reestablishment_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@CS_RAB_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Incoming_External_Inter-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Paging" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Abis_Interface_Paging" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@PS_RAB_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RRC_Reestablishment" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@CS_RAB_Setup_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Packet" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RRC_Connection_Reject" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Intra-RAT_Handover_in_DRX" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Flow_Control" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@PS_RAB_Setup_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Intra-RAT_Handover_over_X2" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@CS_RAB_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@URA_Update" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Cell_Algorithm" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Incoming_Internal_Inter-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Intra-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@E-RAB_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Soft_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Intra-RAT_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Throughput_and_Data_Volume" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RA" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@MCS" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Incoming_Intra-RAT_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Outgoing_Internal_Inter-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Outgoing_External_Inter-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@E-RAB_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RB_Procedure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Hard_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RRC_Connection_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@PRB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Call_Drop" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Inter-RAT_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Security_Mode" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Cell_Update" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@MIMO" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Local Cell@HSDPA_2" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Channel_Quality" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@CQI" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Multi-RAB_Service" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@DRB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Local Cell@HSDPA" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Local Cell@Cell_Traffic" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@MR_upon_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@SDCCH_Call_Drop" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@TRX" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Maximum_Busy_Channel" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Power_Statistics" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@MR_Quantity" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Abis_Interface_Resource" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Channel_Assignment_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Incoming_Inter-RAT_Inter-Cell_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Downlink_GPRS_RLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Power_Control_Message" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@DL_EGPRS_TBF_Estab_and_Rel" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Uplink_GPRS_RLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@KPI" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Uplink_GPRS_TBF_Establishment_and_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Uplink_EGPRS_TBF_Establishment_and_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Channel_Assignment_Request" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@TCH_Call_Drop" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@MS_Capability" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@DL_GPRS_TBF_Estab_and_Rel" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Uplink_EGPRS_RLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Call_Duration" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Channel_Status" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@CSFB_Call_for_Cell" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Compressed_Mode" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Location_Update" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Downlink_EGPRS_RLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Uplink_LLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@PDCH_Resource" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Channel_Configuration" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Speech_Frame_in_Customized_MR" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@Downlink_LLC_Data_Transfer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Incoming_Intra-RAT_Handover_over_X2" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Throughput_and_Data_Volume_1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@UE_Context_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Packet_Size_Distribution" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Throughput_Distribution" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Intra-RAT_Handover_1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@E-RAB_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@UE_Context_Setup_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Throughput_and_Data_Volume_per_Path_Loss_Range" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@RQI_Distribution" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@IPPath@IPPath" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RLC" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Resource_Optimization" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Receive_Quality_Distribution" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@Cell@MR" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Uplink-and-Downlink_Balance" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Radio_Link_Failure_based_on_TA" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@Cell@UE_Context_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@IPPM@IPPM" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@RQI_based_on_TA" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Receive_Quality" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Interference_Band" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@Cell@Outgoing_Inter-RAT_Handover_1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@MR_Quantity_based_on_TA" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@Cell Sector Equipm@SFN_Cell_Sector_Equipment_E-RAB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Radio_Link_Failure" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BTS3900@Cell@Cell_User_Quantity" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Common_Channel" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@UL_Interoperability" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Measurement_of_Channel_Reconfiguration_to_DCH" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@TCHH_Receive_Level" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900GSM@TRX@TCHF_Receive_Level" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900GSM@TRX@Customized_MR" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Algorithm_2" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@CNOperator" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RRC_Status" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@TRX_Status" WHERE "Result Time" <now()::date- 7;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@HSUPA" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell Sector Equip Group@SFN_G_ERAB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@CNOperator@RAB_Release_per_PLMN" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@CNOperator@RAB_Setup_per_PLMN" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@CS_RAB_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@CS_RAB_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@Multi-RAB_Service" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@CS_RAB_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@PS_RAB_Modification" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@PS_RAB_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@PS_RAB_Setup" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@RNC@RAB_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Transmission Resource Pool Local IP Add@IPLayer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@eNodeB@eNodeB_SCTP" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@S1 Link@S1_Link" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@eNodeB@eNodeB_RIM" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@eNodeB@eNodeB_Throughput" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@GSM Cell@User_Defined_Table1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@User_Defined_Table1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@E1T1 Port Bit Error@E1/T1_Port_Bit_Error" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@eNodeB@eNodeB_User_Quantity" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900GSM@TRX@User_Defined_Table1" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@IPPath PM@IPPM" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Interface Board Subsystem@Interf_Subsystem" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@XPU Subsystem@XPU_Subsystem" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@FEGE Ethernet Port@FE/GE_Ethernet_Port" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Transmission Resource Pool Adj Node@UP_Traffic@" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Transmission Resource Pool Adj Node@Trans_Qual" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@NodeB@Iub_per_NodeB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@NodeB@Algorithm_per_NodeB" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@UMTS DSP@DSP" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@IP Path@IPPath" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@IPPath IP Layer@IPPath_IP_Layer" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@NodeB Board@NodeB_Board_Service" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6910UMTS@Subsystem@Subsystem" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@E-RAB_Setup_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Incoming_Inter-RAT_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@MAC" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@RRC_Setup_Failure" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@UE_Context_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BTS3900@Cell@Cell_Emergency_Call" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Inter-RAT_Handover" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@TX_and_RX_Power" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Traffic" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RAB_Release" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@RRC_MR" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Algorithm" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Traffic_Volume_and_Data_Rate" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@Paging" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@BLER" WHERE "Result Time" <now()::date- 15;
DELETE FROM "Hourly"."BSC6900UMTS@Cell@HSDPA" WHERE "Result Time" <now()::date- 15
DELETE FROM "Hourly"."BSC6900UMTS@Cell@CS_Service_Quality" WHERE "Result Time" <now()::date- 15
